server:
  port: 8088
spring:
  application:
    name: consumer_server
  #eureka:
  #  client:
  #    serviceUrl:
  #      defaultZone: http://127.0.0.1:8083/eureka/
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos的服务地址